### ISSUE TITLE
Meeting Minutes and To-Do as discussed by the group

### ISSUE THREAD

**Issue by deepaksidhu** [UBC-MDS/simpler_eda#39]
Meeting Date: March 10, 2021

Finished the Continuous integration for the python package
- update the functions for plotting and tests to support flake8 syntax
- Added Code coverage in build step 
- Successfully run the build.yml

Next Meeting:  March 11, 2021
Time: 7:30 pm

To-do:

- [x] Deployment for python package
- [x] ReadTheDocs for function documentation
- [x] Talk about R packages in the meeting tomorrow

**Comment by ChuckHo777** [comment]
All tasks are completed and checked.
