### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by nichowu** [UBC-MDS/simpler_eda#7]
- [x] team work contract
- [x] add contributors to README.md
- [x] Edit CONDUCT.md 
- [x] edit CONTRIBUTING.md to reflect your strategy
- [x] edit README.md
- [x] function specification

**Comment by nichowu** [comment]
Next meeting: Friday 1:00p.m. 
zoom link; TBD
